#!/usr/bin/env python3
"""Build a consolidated wishlist from your decks — nothing is blocked, it's all
just surfaced so you can decide what to buy.

Pulls together three sources:
  1. Shared singles — cards used in more decks than you own copies of (buy extra
     copies so the decks can be sleeved at once). Priced from your collection.
  2. Not owned — cards in a deck you don't own at all.
  3. Upgrades — entries from any <deck>.buylist.csv.

Writes a checklist to data/wishlist.md (and prints a summary).

Usage:
  python3 wishlist.py --collection data/collection/collection.csv
  python3 wishlist.py --collection coll.csv --out data/wishlist.md
"""
import argparse
import csv
import glob
import os
import sys

import mtglib
import deck_conflicts


def load_buylists(decks_dir):
    rows = []
    for path in glob.glob(os.path.join(decks_dir, "*.buylist.csv")):
        deck = os.path.basename(path).split(".")[0]
        with open(path, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                card = (r.get("Card") or "").strip()
                if not card:
                    continue
                try:
                    price = float(str(r.get("Price", "")).replace("$", "").strip())
                except ValueError:
                    price = None
                rows.append({
                    "card": card, "price": price, "deck": deck,
                    "replaces": (r.get("Replaces") or "").strip(),
                    "reason": (r.get("Reason") or "").strip(),
                })
    return rows


def build(collection_path, decks_dir):
    coll = mtglib.load_collection(collection_path)
    idx = mtglib.index_by_name(coll)
    usage = deck_conflicts.scan(decks_dir, idx)
    conf = deck_conflicts.conflicts(usage)

    shared = [c for c in conf if c["owned"] > 0]          # own some, need more
    unowned = [c for c in conf if c["owned"] == 0]        # own none
    upgrades = load_buylists(decks_dir)
    return shared, unowned, upgrades


def _cost(items, key_qty, key_price):
    return round(sum((i[key_price] or 0) * (i.get(key_qty, 1) or 1) for i in items), 2)


def render_md(shared, unowned, upgrades):
    out = ["# MTG Wishlist",
           "",
           "_Auto-generated by `wishlist.py` from cross-deck conflicts + buy-lists. "
           "Nothing here is required — it's what you'd buy to run everything at once "
           "or to upgrade._", ""]

    share_cost = _cost(shared, "short", "price")
    out.append(f"## Copies to buy so decks can coexist  ~${share_cost:,.2f}")
    out.append("_You use these in more decks than you own copies. Buy the extra "
               "copies, or just don't sleeve those decks simultaneously._\n")
    if not shared:
        out.append("- _none_ ")
    for c in sorted(shared, key=lambda x: -((x["price"] or 0) * x["short"])):
        each = f"~${c['price']:.2f} ea" if c["price"] is not None else "price n/a"
        out.append(f"- [ ] **{c['short']}× {c['card']}** ({each}) — shared by "
                   f"{', '.join(c['decks'])}")
    out.append("")

    out.append("## Cards in a deck you don't own yet")
    if not unowned:
        out.append("- _none_ ")
    for c in sorted(unowned, key=lambda x: x["card"]):
        out.append(f"- [ ] **{c['short']}× {c['card']}** — in {', '.join(c['decks'])}")
    out.append("")

    up_cost = _cost(upgrades, "qty", "price")
    out.append(f"## Upgrades from deck buy-lists  ~${up_cost:,.2f}")
    if not upgrades:
        out.append("- _none_ ")
    for u in sorted(upgrades, key=lambda x: (x["deck"], -(x["price"] or 0))):
        each = f"~${u['price']:.2f}" if u["price"] is not None else "price n/a"
        swap = f" — replaces {u['replaces']}" if u["replaces"] else ""
        out.append(f"- [ ] **{u['card']}** ({each}, {u['deck']}){swap}: {u['reason']}")
    out.append("")

    grand = round(share_cost + up_cost, 2)
    out.append(f"**Rough total (shared + upgrades): ~${grand:,.2f}** — "
               "prices are your export's MARKET / buy-list estimates.")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description="Build a consolidated wishlist.")
    ap.add_argument("--collection", required=True)
    ap.add_argument("--decks-dir", default="data/decks")
    ap.add_argument("--out", default="data/wishlist.md")
    args = ap.parse_args()

    try:
        shared, unowned, upgrades = build(args.collection, args.decks_dir)
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    md = render_md(shared, unowned, upgrades)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(md)
    share_cost = _cost(shared, "short", "price")
    up_cost = _cost(upgrades, "qty", "price")
    print(f"wrote {args.out}")
    print(f"  shared copies to buy : {sum(c['short'] for c in shared)} (~${share_cost:,.2f})")
    print(f"  not owned yet        : {sum(c['short'] for c in unowned)}")
    print(f"  buy-list upgrades    : {len(upgrades)} (~${up_cost:,.2f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
